in_shape:
- 10
- 31
- 256
- 256
hid_S: 64
hid_T: 256
N_S: 4
N_T: 8
aft_seq_length: 20
max_epochs: 50
opt: adamw
lr: 0.001
min_lr: 1.0e-05
warmup_lr: 1.0e-05
warmup_epoch: 10
weight_decay: 0.05
filter_bias_and_bn: true
momentum: 0.9
sched: cosine
decay_epoch: 30
decay_rate: 0.1
loss_weight_focal: 0.0
loss_weight_evo: 0.5
loss_weight_ssim: 0.5
loss_weight_csi: 1.0
use_curriculum_learning: true
_instantiator: lightning.pytorch.cli.instantiate_module
